const fs = require('fs');
const path = require('path');
const { getDb, projectRoot, nowCSTReadable } = require('../shared/db_env');
const defaultOutputFile = path.join(projectRoot, 'database/seed_anime_data.sql');

function escapeSql(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'boolean') return value ? '1' : '0';
  // Escape single quotes by doubling them
  return `'${String(value).replace(/'/g, "''")}'`;
}

function buildInsertStatement(tableName, columns, row) {
  const escapedColumns = columns.join(', ');
  const escapedValues = columns.map((column) => escapeSql(row[column])).join(', ');
  return `INSERT INTO ${tableName} (${escapedColumns}) VALUES (${escapedValues});`;
}

async function main() {
  const outputFile = process.argv[2]
    ? path.resolve(process.argv[2])
    : defaultOutputFile;

  const db = getDb();

  try {
    const animeRows = db.prepare(`
      SELECT *
      FROM anime
      ORDER BY id ASC
    `).all();

    const historyRows = db.prepare(`
      SELECT id, animeId, animeTitle, episode, watchedAt
      FROM watch_history
      ORDER BY watchedAt ASC, id ASC
    `).all();

    const animeColumns = [
      'id', 'title', 'original_title', 'coverUrl', 'localCoverUrl', 'status', 'score',
      'progress', 'totalEpisodes', 'durationMinutes', 'notes', 'tags', 'summary',
      'start_date', 'end_date', 'premiere_date',
      'cast', 'cast_aliases', 'isFinished', 'createdAt', 'updatedAt',
    ];

    const historyColumns = ['id', 'animeId', 'animeTitle', 'episode', 'watchedAt'];
    const nextAnimeId = animeRows.length > 0 ? Number(animeRows[animeRows.length - 1].id) + 1 : 1;
    const nextHistoryId = historyRows.length > 0 ? Number(historyRows[historyRows.length - 1].id) + 1 : 1;

    const lines = [
      '-- Auto-generated by scripts/db/export_anime_seed.js',
      `-- Source: SQLite database`,
      `-- Generated at: ${nowCSTReadable()} (UTC+8)`,
      '-- Shared data only: anime + watch_history',
      '',
      'DELETE FROM watch_history;',
      'DELETE FROM anime;',
      '',
    ];

    for (const row of animeRows) {
      lines.push(buildInsertStatement('anime', animeColumns, row));
    }

    lines.push('');

    for (const row of historyRows) {
      lines.push(buildInsertStatement('watch_history', historyColumns, row));
    }

    // Update sqlite_sequence so AUTOINCREMENT works correctly after import
    lines.push('');
    lines.push(`UPDATE sqlite_sequence SET seq = ${nextAnimeId - 1} WHERE name = 'anime';`);
    lines.push(`UPDATE sqlite_sequence SET seq = ${nextHistoryId - 1} WHERE name = 'watch_history';`);
    lines.push('');

    fs.writeFileSync(outputFile, lines.join('\n'), 'utf8');

    console.log(
      `Exported ${animeRows.length} anime rows and ${historyRows.length} watch history rows to ${path.relative(projectRoot, outputFile)}`
    );
  } finally {
    db.close();
  }
}

main().catch((error) => {
  console.error(error.message || error);
  process.exit(1);
});
